FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && \
    apt-get install -y libgtk2.0-dev && \
    apt-get install -y wget bzip2 ca-certificates curl git vim tmux g++ gcc build-essential && \
    apt-get install -y cmake checkinstall gfortran libjpeg8-dev libtiff5-dev pkg-config yasm && \
    apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libxine2-dev libv4l-dev && \
    apt-get install -y libgtk2.0-dev libtbb-dev libatlas-base-dev libfaac-dev libmp3lame-dev && \
    apt-get install -y libtheora-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev && \
    apt-get install -y libopencore-amrwb-dev x264 v4l-utils libprotobuf-dev protobuf-compiler libgoogle-glog-dev libgflags-dev libgphoto2-dev libhdf5-dev doxygen libflann-dev libboost-all-dev proj-data libproj-dev libyaml-cpp-dev cmake-curses-gui libzmq3-dev freeglut3-dev


# Core Linux tools #####
RUN apt-get update && apt-get install -y --no-install-recommends\
    apt-utils net-tools lsb-release sudo unzip less ssh \
    software-properties-common python3-dev python3-pip clang-12 rsync \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 12 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 12 \
    && python3 -m pip install --upgrade pip \
    && python3 -m pip --version

ARG user=trifinger
ARG group=trifinger
ARG uid=1000
ARG gid=1000
ARG home=/home/${user}
RUN mkdir -p /etc/sudoers.d \
    && groupadd -g ${gid} ${group} \
    && useradd -d ${home} -u ${uid} -g ${gid} -m -s /bin/bash ${user} \
    && echo "${user} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/sudoers_${user}
USER ${user}
RUN sudo usermod -a -G video ${user}
WORKDIR ${home}

RUN cd ${home} && git clone https://github.com/pybind/pybind11 &&\
    cd pybind11 && git checkout v2.10.0 &&\
    mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF &&\
    sudo make -j6 && sudo make install


RUN cd ${home} && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz &&\
    tar xvzf ./eigen-3.4.0.tar.gz &&\
    cd eigen-3.4.0 &&\
    mkdir build &&\
    cd build &&\
    cmake .. &&\
    sudo make install

RUN python3 -m pip install torch torchvision torchaudio &&\
    python3 -m pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" &&\
    python3 -m pip install scipy joblib scikit-learn ruamel.yaml trimesh pyyaml opencv-python imageio open3d transformations warp-lang einops kornia pyrender

RUN cd ${home} && git clone --recursive https://github.com/NVIDIAGameWorks/kaolin
RUN cd ${home}/kaolin && FORCE_CUDA=1 IGNORE_TORCH_VER=1 python3 setup.py develop --user
RUN cd ${home} && git clone https://github.com/NVlabs/nvdiffrast && cd ${home}/nvdiffrast && pip install .

ENV OPENCV_IO_ENABLE_OPENEXR=1


RUN python3 -m pip install scikit-image meshcat webdataset omegaconf pypng roma seaborn opencv-contrib-python openpyxl wandb imgaug Ninja xlsxwriter timm albumentations xatlas rtree nodejs jupyterlab objaverse g4f ultralytics==8.0.120 pycocotools videoio numba h5py lcm

RUN pip install pyrealsense2

